### ISSUE TITLE
Document NPR's bandwidth detection

### ISSUE THREAD

**Issue by marcoscaceres** [w3c-webmob/netinfo-usecases#50]
The NPR application on iOS claims to be able to detect when there is a "slow connection" - when it does so, it displays an alert box. It's not clear how it detects the bandwidth or what it means (could mean latency or raw download speed from their server?). It also seems to do this erroneously as the Wi-Fi connection is at full-strength - so the alert doesn't really help the user as there is nothing he or she can do to rectify the situation.  

![2014-01-02 09 23 07](https://f.cloud.github.com/assets/870154/1830457/a51306c8-7343-11e3-9a80-5fa67acc8ae2.png)

**Comment by marcoscaceres** [comment]
@yoavweiss, you might like this one ^^^  :)

**Comment by yoavweiss** [comment]
This certainly looks like an ad against bandwidth detection :)

Even if bandwidth detection here was correct, notifying the user that "Content may be slow" is completely redundant to existing OS signals such as the radio signal strength, and to the fact that the user sees the content being downloaded slowly.
Adding that notification as an alert that the user has to 'OK' is just rubbing salt into the wound.

This use-case, if it is in fact necessary, can be better served by timing APIs rather than (inaccurate) bandwidth detection.
